site_name: The Timescaledb gem
repo_url: https://github.com/jonatas/timescaledb
edit_uri: edit/master/docs/
extra:
  analytics:
    provider: google
    property: G-9B2BMB0TNQ
theme:
  name: material
  palette:
    primary: indigo
    accent: pink
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introduction: index.md
  - Migrations: migrations.md
  - Models: models.md
  - Command Line: command_line.md
  - Videos: videos.md
